### ISSUE TITLE
Missing HTTPS

### ISSUE THREAD

**Issue by haf** [ionide/ionide.github.io#14]
The site should be HTTPS nowadays.

Tell me if you have problems doing this and I might be able to co-host you at Suave.io.

**Comment by peterzeller** [comment]
Basically this should be automatic with Github pages nowadays (see https://blog.github.com/2018-05-01-github-pages-custom-domains-https/). Probably you just have to update the domain record or the Github settings.

**Comment by peterzeller** [comment]
@haf I meant "you" = owners of the domain / repository. So this issue should stay open until they enabled https.
