### ISSUE TITLE
The toolchain graph isn't showing up in firefox.

### ISSUE THREAD

**Issue by TheAngryByrd** [ionide/ionide.github.io#18]
**Describe the bug**
The toolchain graph isn't showing up in firefox.  I haven't looked for a corresponding bug on mermaid's repository yet. 

**To Reproduce**
Goto ionide.io in Firefox on Windows

**Expected behaviour**
Should show a graph

**Screenshots**

<img width="1031" alt="image" src="https://user-images.githubusercontent.com/1490044/213018957-3dced444-f786-47e6-b833-bd32ad5b7a7d.png">

**Environment (please complete the following information):**
 - Browser: Firefox

**Comment by dawedawe** [comment]
I think, this can be closed. At least, it works here™️

**Comment by TheAngryByrd** [comment]
Thanks for checking! Works here now too.
